spring:
  profiles:
    active: test
---
server:
  port: 5202
spring:
  profiles: test
  application:
    name: microservice-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
---
server:
  port: 5211
spring:
  profiles: dev
  application:
    name: microservice-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka

